


deploy:
  provider: releases
  api_key:
    secure: f6WCfS2m2lLrg+VDmQgZV1HJoqVhJCMmJPfVdsoWiQD/pa5pPNtKY4opUMK4IPGUTV/wSdljUigrxH8h2/hY2JbmOBxpyneOQYJifEkmI9tjm89Yxd3GOgXYFzdxNyGJyYkF5IyUzBUp8uYNrZEar8MwzVUkCX7p647YUr/mWPCymKIde9hrB1ynBCnBx54d+Usxvkxme/tZFjGmOkMjA53unqeCodZeUpkMuB4Vvytzhxh9tI3ILC9wIQqxvzCu2iCv3VeZhXA0f35tnNPKmnf6aQ0Dz73G3N4wyu3MVeR3JjUPPN57/hL3oOMCz9+PhUHL3VWYIo7PFFiOWCLhZcPUDRJXNbtffI7YwqcPSYK2U7SPjmpxj2mj9+lCnXM72mDn/bclYlW80Ti3SLdNAke53JXDpvEybXSpTXjmlmne8Tb/AwAAZY6j/g4LTMH6/ko1z3JpV1pOtRLkzCLv/5ezn+qt1VtPW2/AWugjQfyPT6vov9k0gdOWiWtX3rqzTOIuqySv95qfue64pX4KGiiMWGv1Gkqj1/ogGChk2GvcGaxRkLrhvbJ4OgvenauCoBRqJDHQq816bPC6d8QLJLX64WDdmgC0hCsnLvOQSmrnKtBUtIbZQ/fRfChDZOs0vkqruBNaiTvtp73AgWcVepJ6L6QGAo1ioj4Fw1mNt+Y=
  file: $TRAVIS_BUILD_DIR/.pioenvs/nodemcu/firmware.elf
  on:
    repo: albertsuwandhi/pio-travisci
